### ISSUE TITLE
Не сохраняет последнюю игру из списка

### ISSUE THREAD

**Issue by NatashaBazunova** [Denis063/TeamProject#3]
# Описание
При проверке наличия игры в каталоге возвращает false именно на последнюю игру из всего списка. Остальные игры возвращает true.

# Локация дефекта
https://github.com/Denis063/TeamProject/blob/ea0024cd736adfbfc4dd06fdf0f31dbd09fbe2f4/src/main/java/ru/netology/GameStore.java#L32

# Шаги воспроизведения
1.  Открыть [код программы](https://github.com/Denis063/TeamProject/blob/gamestore/src/main/java/ru/netology/GameStore.java#L32) в IDEA.
2. Заполнить список игр путем вызова метода publishGame .
3. Вызвать метод containsGame, указав последнюю игру из списка (game4).

*Ожидаемый результат*: true
*Фактический результат*:false

# Скриншот

![containsGame](https://user-images.githubusercontent.com/95566131/169513204-7715b4a5-3e1e-4d08-9f11-c70522d9bc3e.jpg)

# Окружение

* **Операционная система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA 2021.3.1 
* **JDK:** OpenJDK 11

**Comment by Denis063** [comment]
При запуске исходного теста при добавлении всего одной игры тест также не проходит

*Ожидаемый результат:* true
*Фактический результат:* false

# Скриншот
![Bug1](https://user-images.githubusercontent.com/99782325/169520394-8d01a83b-2ab4-4329-94d0-7f2a05d05737.png)

# Окружение
* **Операционная система:** Windows 10 Домашняя для одного языка
* **IDE:** IntelliJ IDEA 2021.3.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Denis063** [comment]
Баг устранен, тест проходит

# Скриншот
![Fix1](https://user-images.githubusercontent.com/99782325/169525919-fe310207-6065-4d33-bbf9-5ecef5908379.png)

# Скриншот
![Fix1-1](https://user-images.githubusercontent.com/99782325/169525980-0b1ea272-ce7a-4a62-9d42-c1b344a5a38a.png)

**Comment by Denis063** [comment]
Модификация boolean containsGame

![Fix1-1-1](https://user-images.githubusercontent.com/99782325/169759417-b343ff62-eec2-4312-a3d2-bac984604071.png)
