### ISSUE TITLE
Не суммирует общее количество времени всех игроков

### ISSUE THREAD

**Issue by NatashaBazunova** [Denis063/TeamProject#4]
# Описание
Не суммирует общее игровое время. Проблема распространяется как для одного игрока, так и для нескольких.

# Локация дефекта
https://github.com/Denis063/TeamProject/blob/ea0024cd736adfbfc4dd06fdf0f31dbd09fbe2f4/src/main/java/ru/netology/GameStore.java#L75

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Denis063/TeamProject/blob/gamestore/src/main/java/ru/netology/GameStore.java#L75)
2.  Заполнить список игроков и время, проведенного в игре путем вызова метода addPlayTime: 
(store.addPlayTime("Alex", 10); store.addPlayTime("Evgen", 11); store.addPlayTime("Sasha", 4);
4.  Вызвать метод getSumPlayedTime, указав суммарное игровое время игрока(ов) в поле expected.(

* *Ожидаемый результат:*  25
*  *Фактический результат:* 0

# Скриншот
![GetSumPlayTime](https://user-images.githubusercontent.com/95566131/169525373-a36a99dc-2bc3-43f5-9b6b-2b380cce7f1e.jpg)

# Окружение
* **Операционная система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA 2021.3.1
* **JDK:** OpenJDK 11

**Comment by Denis063** [comment]
Баг устранен. Тесты проходят.

# Скриншот
![Fix2-1](https://user-images.githubusercontent.com/99782325/169757157-c74b1edf-f2d9-48f3-9b3d-7c1b37b9e51e.png)


# Окружение
* **Операционная система:** Windows 10 Домашняя для одного языка
* **IDE:** IntelliJ IDEA 2021.3.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Denis063** [comment]
Модификация getSumPlayedTime

![Fix2-1-1](https://user-images.githubusercontent.com/99782325/169759726-18d64a2d-0771-4e05-b484-385cc9a103eb.png)
